### ISSUE TITLE
is it possible to use koa-passport without session?

### ISSUE THREAD

**Issue by thewillhuang** [rkusa/koa-passport#36]
Hello, just building a restful api for an ios application, i was trying to use json web token to authenticate all my api end points...

ended up hitting a snag

```js
// callback version
passport.use(new LocalStrategy({session: false},
  function(username, password, done) {
    pool.getConnection(function(connectionError, connection) {
      console.log('connection error', connectionError);
      const q = {};
      q.sql = 'SELECT ?? FROM ?? WHERE ?? = ?';
      q.values = ['userPwHash', 'user', 'userName', username];
      connection.query(q, function(err, rows) {
        console.log('query error', err);
        console.log('rows', rows);
        if (err) {return done(err); }
        if (!rows.length) {
          return done(null, false, {message: 'Incorrect username.'});
        }
        const dbpwhash = rows[0].userPwHash;
        bcrypt.compare(password, dbpwhash, function(hashError, match) {
          console.log('hasherror', hashError);
          if (match) { return done(null, {userName: username}); }
          if (!match) {return done(null, false, {message: 'Incorrect password.'}); }
        });
        connection.close();
      });
      // pool.end();
    });
  }
));
```

```bash
Error: Failed to serialize user into session
      at pass (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/passport/lib/authenticator.js:277:19)
      at Authenticator.serializeUser (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/passport/lib/authenticator.js:295:5)
      at Object.req.login.req.logIn (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/passport/lib/http/request.js:48:29)
      at /Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:136:8
      at thunkToPromise (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:135:10)
      at toPromise (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:119:55)
      at next (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:99:29)
      at onFulfilled (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:69:7)
      at /Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:54:5
      at co (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:50:10)
      at toPromise (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:118:63)
      at next (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:99:29)
      at onFulfilled (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:69:7)
      at /Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:54:5
      at co (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:50:10)
      at createPromise (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/co/index.js:30:15)
      at Strategy.strategy.success (/Users/William/workspace/UnitedNurseRegistry/node_modules/koa-passport/node_modules/passport/lib/middleware/authenticate.js:194:18)
      at verified (/Users/William/workspace/UnitedNurseRegistry/node_modules/passport-local/lib/strategy.js:83:10)
      at /Users/William/workspace/UnitedNurseRegistry/server/services/auth.js:34:14
      at tryCatcher (/Users/William/workspace/UnitedNurseRegistry/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (/Users/William/workspace/UnitedNurseRegistry/node_modules/bluebird/js/main/promise.js:503:31)
      at Promise._settlePromiseAt (/Users/William/workspace/UnitedNurseRegistry/node_modules/bluebird/js/main/promise.js:577:18)
      at Async._drainQueue (/Users/William/workspace/UnitedNurseRegistry/node_modules/bluebird/js/main/async.js:128:12)
      at Async._drainQueues (/Users/William/workspace/UnitedNurseRegistry/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/William/workspace/UnitedNurseRegistry/node_modules/bluebird/js/main/async.js:15:14)
      at processImmediate [as _immediateCallback] (timers.js:371:17)
```

i was wondering if session is required or how i would go about using an auth token for authentication. thanks again!

**Comment by rkusa** [comment]
I've never used local strategy without a session, but the error sounds like it expects the serialize/deserialize callbacks, despite having session disabled.

**Comment by thewillhuang** [comment]
i added sessions and the serialize/deserialize callbacks and it worked. i also didn't think it was necessary even though i did set session to false, oh well haha.. thanks again!

**Comment by thewillhuang** [comment]
I figured out why i was getting such an error even when i added {session: false} flag. I was using the custom function with the example

```js
public.post('/custom', function*(next) {
  var ctx = this
  yield passport.authenticate('local', function*(err, user, info) {
    if (err) throw err
    if (user === false) {
      ctx.status = 401
      ctx.body = { success: false }
    } else {
      yield ctx.login(user)
      ctx.body = { success: true }
    }
  }).call(this, next)
})
```

```js
ctx.login(user); 
```

according to the passport docs is used to establish a login session. its def a error on my part.

**Comment by Globik** [comment]
@thewillhuang  is custom post for an ajax call? And how to implement errors messages with a normal way by login?

**Comment by thewillhuang** [comment]
@Globik this is how i did mine, granted it could be cleaner but it works
```js
'use strict';

const passport = require('koa-passport');
const LocalStrategy = require('passport-local').Strategy;
const FacebookStrategy = require('passport-facebook').Strategy;
const BearerStrategy = require('passport-http-bearer').Strategy;
const StripeStrategy = require('passport-stripe').Strategy;
const query = require('./query');
const validatePw = require('./validatePassword');
const genHash = require('./genHash');
const jwt = require('./jwt');

// custom error functions
function NoAccountError(message) {
  this.message = message;
  this.name = 'NoAccountError';
  Error.captureStackTrace(this, NoAccountError);
}
NoAccountError.prototype = Object.create(Error.prototype);
NoAccountError.prototype.constructor = NoAccountError;

function EmailTaken(message) {
  this.message = message;
  this.name = 'EmailTaken';
  Error.captureStackTrace(this, EmailTaken);
}
EmailTaken.prototype = Object.create(Error.prototype);
EmailTaken.prototype.constructor = EmailTaken;

function UserExist(message) {
  this.message = message;
  this.name = 'UserExist';
  Error.captureStackTrace(this, UserExist);
}
UserExist.prototype = Object.create(Error.prototype);
UserExist.prototype.constructor = UserExist;

// local strategy -- login
passport.use(new LocalStrategy({
  usernameField: 'email',
  passwordField: 'password',
  session: false,
},
  function (email, password, done) {
    const q = {};
    q.sql = 'SELECT ??, ?? FROM ?? WHERE ?? = ?';
    q.values = ['userPwHash', 'userID', 'User', 'email', email];
    query(q).bind({}).then(function (result) {
      // console.log(result);
      if (result.rows.length === 0) { throw new NoAccountError('no such user found'); }
      this.userID = result.rows[0].userID;
      return validatePw(password, result.rows[0].userPwHash);
    }).then(function (isMatch) {
      // console.log(this.userID);
      return !isMatch ?
        this.done = [false, { message: 'incorrect password' }] :
        this.done = [
          { email, scope: { userID: this.userID } },
          { message: 'Auth Success' },
        ];
    }).catch(NoAccountError, function () {
      this.done = [false, { message: 'incorrect email' }];
    }).catch(function (e) {
      console.log(e);
      this.done = [false, { message: e }];
    }).then(function () {
      return this.done;
    }).asCallback(done, { spread: true });
  }
));
```

**Comment by devt3000** [comment]
Hey, this didnt solve my issue though, #124 .
