### ISSUE TITLE
Flash message

### ISSUE THREAD

**Issue by livemirsi** [rkusa/koa-passport#64]
Hi. I try use flash message:
`router.post('/user/auth/', passport.authenticate('local', {
    successRedirect: '/',
    failureRedirect: '/user/login/',
    failureFlash: true
}));`
In local strategy:
`done(null, false, { message: 'Incorrect username or password' });`
i get error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: req.flash is not a function
    at allFailed (/home/artem/projects/website/files/node_modules/passport/lib/middleware/authenticate.js:118:15)
    at attempt (/home/artem/projects/website/files/node_modules/passport/lib/middleware/authenticate.js:167:28)
    at Strategy.strategy.fail (/home/artem/projects/website/files/node_modules/passport/lib/middleware/authenticate.js:284:9)
    at verified (/home/artem/projects/website/files/node_modules/passport-local/lib/strategy.js:82:30)
    at /home/artem/projects/website/files/modules/auth/index.js:22:6
    at Query.<anonymous> (/home/artem/projects/website/files/node_modules/mongoose/lib/model.js:3352:16)
    at /home/artem/projects/website/files/node_modules/kareem/index.js:244:21
    at /home/artem/projects/website/files/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
How to fix this error?

**Comment by rkusa** [comment]
Hi, does #35 help?

**Comment by livemirsi** [comment]
Yes. Thank you very much!

**Comment by rkusa** [comment]
You are welcome!
