### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by rubenv** [rkusa/koa-passport#8]
Passport has a `login` method: http://passportjs.org/guide/login/

How do I use that with `koa-passport`?

The following fails:

``` js
        var user = yield User.getForSession(userId);

        yield this.login(user);
        this.body = {
            ok: 1
        };
```

With this error:

```
TypeError: undefined is not a function
    at /Users/ruben/Projects/Savanne/datahub/node_modules/passport-remember-me/node_modules/passport/lib/passport/http/request.js:46:7
    at Authenticator.passport.serializeUser (/Users/ruben/Projects/Savanne/datahub/src/common/auth.js:28:5)
    at IncomingMessage.req.login.req.logIn (/Users/ruben/Projects/Savanne/datahub/node_modules/passport-remember-me/node_modules/passport/lib/passport/http/request.js:43:29)
    at Object.<anonymous> (/Users/ruben/Projects/Savanne/datahub/src/webui/handlers/activate.js:48:20)
    at GeneratorFunctionPrototype.next (native)
    at Object.next (/Users/ruben/Projects/Savanne/datahub/node_modules/koa/node_modules/co/index.js:83:21)
    at /Users/ruben/Projects/Savanne/datahub/node_modules/koa/node_modules/co/index.js:102:18
    at /Users/ruben/Projects/Savanne/datahub/node_modules/koa/node_modules/co/index.js:222:7
    at tryCatch1 (/Users/ruben/Projects/Savanne/datahub/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/ruben/Projects/Savanne/datahub/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/ruben/Projects/Savanne/datahub/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/ruben/Projects/Savanne/datahub/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/ruben/Projects/Savanne/datahub/node_modules/bluebird/js/main/promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/ruben/Projects/Savanne/datahub/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/Users/ruben/Projects/Savanne/datahub/node_modules/bluebird/js/main/async.js:37:14)
    at process._tickCallback (node.js:343:11)
```

Which seems to indicate that it's complaining about not having a `done` function.

**Comment by m-brian** [comment]
It seems like after you restored `this.req.user` in 0.5.x, `login()` is yet again not yieldable.

**Comment by rkusa** [comment]
The `/custom` route, wich yields `login()`, in [`koa-passport-example`](https://github.com/rkusa/koa-passport-example/blob/master/server.js#L38:L50) still works. Do you have an example of not working code?
